---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: myblog
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/myblog
  prune: true
  sourceRef:
    kind: GitRepository
    name: myblog