---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: myblog
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/yungen-lu/My-Blog