---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: ingress-system
  name: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: jetstack-helmchart
  values:
    installCRDs: false