---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: media
  name: qbittorrent
spec:
  interval: 1h
  chart:
    spec:
      chart: qbittorrent
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: k8s-at-home-helmchart
      interval: 10m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        # nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.100.0/16"
      tls:
        - secretName: torrent-k3s-yungen-studio-tls
          hosts:
            - torrent.k3s.yungen.studio
      hosts:
        - host: torrent.k3s.yungen.studio
          paths:
          - path: /
            pathType: Prefix

    env:
      TZ: Asia/Taipei
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        storageClass: managed-nfs-storage
        size: 1Gi
      downloads:
        enabled: true
        mountPath: /downloads
        storageClass: managed-nfs-storage
        accessMode: ReadWriteMany
        size: 500Gi
      media:
        enabled: true
        mountPath: /media
        existingClaim: "jellyfin-media"