---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: storage-system
  name: nfs-subdir-external-provisioner
spec:
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: nfs-subdir-external-provisioner-helmchart
      interval: 1h
  values:
    nfs:
      server: 192.168.100.201
      path: /nfs
      # mountOptions:
    storageClass:
      name: managed-nfs-storage
      pathPattern: ${.PVC.namespace}-${.PVC.name}
