---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: ingress-system
  name: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: jetstack-helmchart
      interval: 10m
  values:
    installCRDs: true