apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # namespace: cert-manager
  name: letsencrypt-staging
spec:
  acme:
    email: yungen.lu@outlook.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
          