---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: 2.3.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-helmchart
        namespace: flux-system
  values:
    configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.100.210-192.168.100.250
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.9.6
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.9.6