---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: nextcloud-helmchart
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.5.4
  interval: 1h
  values:
    image:
      repository: nextcloud
      tag: 20.0.4-apache
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 50G
      hosts:
        - host: nextcloud.k3s.yungen.studio
          paths: [/]
      tls:
        - secretName: jellyfin-k3s-yungen-studio-tls
          hosts:
            - jellyfin.k3s.yungen.studio

    persistence:
      enabled: true
      storageClass: nfs-storage
      accessMode: ReadWriteOnce
      size: 250Gi

    resources:
      requests:
        cpu: 1 # 2 seems too aggresive 
        memory: 1Gi

    nextcloud:
      host: nextcloud.k3s.yungen.studio
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: admin-username
        passwordKey: admin-password

      phpConfigs:
        upload.ini: |-
          upload_max_filesize=10G
          post_max_size=10G
          memory_limit=4G
      # configs:
      #   https.config.php: |-
      #     <?php
      #     $CONFIG = array (
      #       'overwriteprotocol' => 'https'
      #     );

      # extraVolumes:
      #   - name: jellyfin-media
      #     persistentVolumeClaim:
      #       claimName: jellyfin-media

      # extraVolumeMounts:
      #   - name: jellyfin-media
      #     mountPath: /jellyfin-media

      extraEnv:
        - name: REDIS_HOST
          value: nextcloud-redis
        - name: REDIS_HOST_PORT
          value: "6379"

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgres
      existingSecret:
        enabled: true
        secretName: nextcloud-postgres-secret
        usernameKey: postgres-username
        passwordKey: postgres-password

    livenessProbe:
      enabled: true
      initialDelaySeconds: 800 # first install is slow in rsync
    