---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: media
  name: jellyfin
spec:
  interval: 1h
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: k8s-at-home-helmchart
      interval: 1h
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        # nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.100.0/16"
      tls:
        - secretName: jellyfin-k3s-yungen-studio-tls
          hosts:
            - jellyfin.k3s.yungen.studio
      hosts:
        - host: jellyfin.k3s.yungen.studio
          paths:
          - path: /
            pathType: Prefix
    
    persistence:
      config:
        enabled: true
        storageClass: managed-nfs-storage
        size: 1Gi

      media:
        enabled: true
        storageClass: managed-nfs-storage
        size: 2Ti
        accessMode: ReadWriteOnce

    # resources:
    #   requests:
    #     cpu: 1
    #     memory: 500Mi

