---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: longhorn-system
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: longhorn-helmchart
      version: 1.1.0
      interval: 1h

  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.100.0/16"
      tls:
        - secretName: longhorn-k3s-yungen-studio-tls
          hosts:
            - longhorn.k3s.yungen.studio
      hosts: longhorn.k3s.yungen.studio

    defaultSettings:
      backupTarget: nfs://192.168.100.201:/nfs
      defaultDataPath: /longhorn
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
    
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      reclaimPolicy: Delete
      