apiVersion: v1
data:
    FLOOD_OPTION_QBUSER: ENC[AES256_GCM,data:qPZ3mwy8,iv:KlmhLY/zLSiyPdNRkOUSwS8xo+2Rsanvu44Xd10pOCg=,tag:v9KQrPKfpKsqjGjxp1FY+Q==,type:str]
    FLOOD_OPTION_QBPASS: ENC[AES256_GCM,data:hpjc+BfYYSDGRifc9+Y=,iv:019worWOa3hRDardZco9tWe05ZaKbqililLmOPwY+cI=,tag:CpR6MixQQSHdZPkzgDTMAA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: qbittorrent-secret
    namespace: media
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-05T03:50:53Z'
    mac: ENC[AES256_GCM,data:0gRK3sEooWRgDHzlPG9vHcpmsrThGfMANztr74lr1/vQH8yJdTYtEcHt79GOzMOAsEiVHFbiiVbFPFwsua42BEEK4wjHQMw9578xscukf57C5b0pWovGSeG9XcizV29klUwSvJkfOST6EyBPoOWZEPH95zMcRVNZoEjwUH2E/wg=,iv:N3AKcMcHENH1n4sEkKLkX3N6KfI2bKKfUIxQ2hkOqNw=,tag:kjT1PfyT+Oevy/Xh5m8LIw==,type:str]
    pgp:
    -   created_at: '2021-03-05T03:50:51Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9srMGl3yb5cARAAn7NkFJ7erp/wvk+UPmwA/gFX/H5TObmpToMO7s6syzRU
            QtRDHu6m3EDBptinQXgT9OyIqQ+q5rmdz44SAQyPquKcaVuzHMjkuuFt8uZe89Kz
            dXwRQDhGzjz0hq+IxICPH/oA3v6atuvu5I2weRs6Iff7PhveHtjXUfekI8WxtkHg
            6Z9TEpxpBkoOCYQNiLiPnAxsplDsdluGizLlpaFb4RsL1p6cLujrmylq59nKizUH
            4x522xkVv/deJgaRao5APr3O5jmykS0hz1nP8AHxdI3f3q3E93iq04dX/y6RjDX4
            o8Y0qokbF5/aaP7nVg687B+FVrWfbpKJ1LmHXrzWI95aijDrzRgI/CfD4okkSLy3
            mC9i2nwBrjFqQI3z2qYSUpyganbrBrgoOeG54eSDWX9GrXkPfzY8e254Arr172Lt
            fNTGOlUN3dc0upjqTzL+AQC9Pk45DWzBASGTmcl395i5pyKqF/u4bWkqxQnVMdBf
            6WKT0CvNLd3fOiXRs7Ypgl6eyn+2aZHq23cEkAdZ3N6pJHU3xj8q3Egh+tFbmJPs
            UD17X2h29bRWQp9ybqpUMX4iAj3xGIgbwg1oFtReBshiXoVgnecjwdWkPglg1+v/
            cnThx8VQVQAdnMhq2fluDo7RmyNJRXPGdhW21/mtsvDDKvb9LqcU24G38PLOmV/S
            XgEFHcL5U0G2bA0buyZ76PUZvbR+Q9TCGwIgQdHnLAhk8gn7HrejoRqgE+VMV6AZ
            FjjP1I/Mqca1GSDmRuq0h6LlJc+j99v6qoUoldgGFdn0oKaPpPWcXO4+2RTJuIQ=
            =yfnb
            -----END PGP MESSAGE-----
        fp: 84F1BAB644790128E06E1830FD45011C8AD0A5FB
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
