---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: monitor-system
  name: kube-prometheus-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: prometheus-community-helmchart
      interval: 1h
  values:
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - grafana.k3s.yungen.studio
        tls:
        - secretName: grafana-k3s-yungen-studio-tls
          hosts:
            - grafana.k3s.yungen.studio
      admin:
        existingSecret: grafana-secret
        userKey: admin-user
        passwordKey: admin-password
    kubeEtcd:
      enabled: false
    kube-controller-manager:
      enabled: false
    alertmanager:
      enabled: false
    kubeScheduler:
      enabled: false
    # prometheus-node-exporter:
    #   tolerations:
    #   - key: "arm"
    #     operator: "Exists"
    #   - key: "armhf"
    #     operator: "Exists"
    prometheus:
      prometheusSpec:
        retention: 3d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: local-path
              resources:
                requests:
                  storage: 8Gi