---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: monitor-system
  name: kube-prometheus-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: prometheus-community-helmchart
      interval: 1h
  values:
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.100.0/16"
        hosts:
          - grafana-stack.k3s.yungen.studio
        tls:
        - secretName: grafana-stack-k3s-yungen-studio-tls
          hosts:
            - grafana-stack.k3s.yungen.studio
      admin:
        existingSecret: grafana-secret
        userKey: admin-user
        passwordKey: admin-password