apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:Zp3Xb9dHb/X8Eb3TFY8JkkpGFS0=,iv:LebGXbZUF/rFNCb/N5UBGO/3zDN9ErBk9Yuu/Ze87dk=,tag:E8Eyw6tSZ9URQ+fKqr5Yxg==,type:str]
    admin-user: ENC[AES256_GCM,data:FO4nqRNZhBI=,iv:qAnSUto5Y3DyrTsUOWXa6OBjYNkPy6dLeyRFFvR8UEA=,tag:0ENdhTqrsnlScphpsC+zDQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-secret
    namespace: monitor-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-14T05:41:46Z'
    mac: ENC[AES256_GCM,data:PJOWFEIHrIKAjlEciEumjlVah1uYlg5KVqNKTaZ8fbZuXrX6eMjVeorjYJYD7aM0PRTAorS0wR4XR257VEA9aadtz9AGXSx80QvPjQ/z8yaubb+wDt6D5vJKv8TfCaWPasbj5hbQoy/56DRt7vKbw1b1QHjKIOtnUv5WV9P8YX0=,iv:7oxX/D6yMOEwWnYdZ+oSEQ82lj7qbEZ2m2rVM0pGdI8=,tag:kHDhvymQd8yyme5F6wBBMQ==,type:str]
    pgp:
    -   created_at: '2021-03-14T05:41:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9srMGl3yb5cAQ/9FuSmyc8+IsjDRe7bEizGIK7GGTMI+mPE6k58XKwKTfOF
            TIoifHZeUTAGNDbvGQEaZFmL7dSTmu8ZtLLvZHPj1IfjvwVTyLJxRBhS0I5Fj+ks
            gYGrFrZquamBrVwm8lw0oyH1SRl2R68jcpX0GzDpet0NQ/QBl7uChzTRgRSTZ9+h
            V/rwJWCQOsnnb/8gB0hCVt9mRD5tGCCZb0APswf11jHUdrGYiEly9MAhngunYq0l
            edl9gOh/0/SL+lN2Xqyuu1I2sAWabKYkm/6s2hP8SozDIHD9wAAA5uJ15N4NMX+J
            J6z8ybZ7+Jsk9SY9kal/4BxRXknTm998uHjqQl0EXp8OruD3zuPbb+aiOmO1PvBR
            hHenhVqhZPIRteiCI2OvM69m8+apvioxu2BL3HLMgfyl2M/wByQh7zNbUEvJGzU8
            OyUdhh1XdZtIXFOjemntZYUSzUn6IbjLOcw3/ZR1mF/oOtiwK0hRlpqfDHJ0RN3g
            cRVOiE2fGqlfB8xMKLL7X7P3V4NgVukLAj7pkPgM9XmlzbS8gWQdTsiAci2C14t9
            jp95cnilfDjR04YITQKGZ7YmZ35UMRGhH1zjQXNQCQ+1TgzK518R2DNYHoS6Gzra
            Z8w+4b64oM5Ijy3GEYmfan0GxXxvs/yPCi2ULFa4m+fo/vknRXj936zeDUII0mnS
            XgFlE2J6H6448j7yIUCheu1jNcPd0rauj2OZvlAKdKcra2KxMR6oUswls5A/rgYK
            OfcSSoFua0ah0Q2ZfPhyRYgpzUDAcLIJt5M4Zj0Dn3FHyzXD29x+gWi9bYl1WUo=
            =4QuD
            -----END PGP MESSAGE-----
        fp: 84F1BAB644790128E06E1830FD45011C8AD0A5FB
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
