apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - nginx.yaml

configMapGenerator:
  - name: webdav-conf
    files:
      - conf/nginx.conf
  # - name: password
  #   files:
  #     - conf/.htpasswd