apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:V1Dql4eVOALXNM3I6JnSvTcMkQEWbkqHcd/q670nRs2I0iD68iBU5EGW2lqH73Ehb2FmtyChlv1aG6eO,iv:m7Nc6o63s9ELRCPv3HfYZtcWIUXIEUeDRAgGNFL+DPc=,tag:KkKBgv4NA/zu0YMJYa0W/g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: webdav-secret
    namespace: media
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-15T01:52:47Z"
    mac: ENC[AES256_GCM,data:gX/wZtNiqzkjgbR8FyjgT6IjcTTQhKpEbpnXkekdImjfWdgA6XK5KBg8w04WPZ5X3hMskKV8IFI8pQFySz74OeRJHi5oL10/3OuSTXZa3AVp5EpgAMaePJVimr2/rJVsKMzc+VAL3WQygbeM94eDJyHAjhpFERp2oKzGYlAUljg=,iv:is05THCJ1m3zC/hRGNDIjoe57OmFPnuNqaBEDwYdsKo=,tag:boF7fQrVr4djDNUm2rNeXA==,type:str]
    pgp:
        - created_at: "2021-05-15T01:52:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9srMGl3yb5cAQ/+LB+cihsO8aDGkGPwzZ1v+yXRCA3V4yjRpYO78eX617yp
            fUT81+Pvo/4sitMiuaKOs4FIL4NH2tS/houmcw1vvMPDiMMEmVk9grb6q3ujOBPk
            NGPiits/1OyGXuPDp9mPnhhyGpBuEe2t/aTMUvpVdoiq9kAnaYlENqf83KvtNR91
            WA6uKFOYLK89es5GDHfzPgFCvRACZo2+JHbHsUqoQezXxCDVmW4dTDExTIHMNUgO
            nrPl2SBNi1Xm6UtexCo8WAgpD1QTSEg8H8MKINfPGf8Dji0itu1C0u05MMjZp/up
            nTftF21w5pFC0FuO/735xmZCpZnsnmNsB8CU0qdY8zsqRW6Gkx3hjo8ZmcaavtZA
            SW/kkYZNXQsFkoBAOSEDYaLWmGdL+K1ngW1IjV0hYamO65T/tcoEcllboBOyZMCU
            aRT7uqhrMDcyXq1LUy8hrXUhce9pbmETyOxbcG5OhZFrjDhIa8I4No+ERT29vcf4
            8hTdaLivd3bqeQUpkEqfi3pjd5Cx0KGnBzdYRhQlSjXBh9GwtWe1vNm3GMRVU/UD
            t6Z+RV+CzxDL5NvQqWCJFVBUMN9dorZwtMEQDZSkmtNOLgFgSEadV+ZylajvI/gC
            5Krcv1Vv6gIqbPmoqcSa/39WCLoy03muLNyku0ef6gbAnG0PDPc7U5q4u6xzZsnS
            XAFnmOpziZwJ3tsEDUwRzHdCCIF7XihBZzkW8JAj7NTmLF+fkctosbhyWjYbxBRK
            wBeiktqrg84glmgJqb7oefzIFUkt40l5ILU+q2fE8k6iJMYe7h+ozxWYYMe3
            =wxvW
            -----END PGP MESSAGE-----
          fp: 84F1BAB644790128E06E1830FD45011C8AD0A5FB
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword|userDatabase)
    version: 3.7.1
