---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: longhorn-system
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: longhorn-helmchart
  values:
    ingress:
      enabled: true
      host: longhorn.k3s.yungen.studio
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.100.0/16"
      tlsSecret: longhorn-k3s-yungen-studio-tls
      tls: true
    defaultSettings:
      defaultDataPath: /storage
      # defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn