---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: storage-system
  name: nfs-subdir-external-provisioner
spec:
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: nfs-subdir-external-provisioner-helmchart
  values:
    nfs:
      server: 192.168.100.202
      path: /nfs
      # mountOptions:
    storageClass:
      name: nfs-storage
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      archiveOnDelete: true
      pathPattern: ${.PVC.namespace}-${.PVC.name}
