---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/crd
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: source
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/source
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/infra
  prune: false
  dependsOn:
    - name: source
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/app
  prune: true
  dependsOn:
    - name: source
    - name: crd
    - name: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-gpg
