---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nextcloud-helmchart
  namespace: flux-system
spec:
  interval: 24h
  url: https://nextcloud.github.io/helm/
  timeout: 3m

