---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: weaveworks-kured-helmchart
  namespace: flux-system
spec:
  interval: 1h
  url: https://weaveworks.github.io/kured
  timeout: 3m